backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/projects'
public_folder: '/assets/projects'

collections:
  - name: 'projects'
    label: 'Projekty'
    folder: 'src/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Název projektu', name: 'title', widget: 'string' }
      - { label: 'Popis', name: 'description', widget: 'text' }
      - { label: 'Obrázek', name: 'image', widget: 'image' }
      - { label: 'Dokončeno', name: 'completed', widget: 'string' }
