backend:
  name: git-gateway
  branch: main
media_folder: 'src/assets/projects'
public_folder: '/assets/projects'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      # - { label: 'Slug', name: 'mySlug', widget: 'string' }
      # - { label: 'Author', name: 'author', widget: 'string', required: false }
      # - {
      #     label: 'Tags',
      #     name: 'tags',
      #     widget: 'list',
      #     default: ['post'],
      #     required: false,
      #   }

      # - {
      #     label: 'Alt Text',
      #     name: 'imageAlt',
      #     widget: 'string',
      #     required: false,
      #   }
      # - { label: 'Body', name: 'body', widget: 'markdown' }
