backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/projects'
public_folder: '/assets/projects'
collections:
  - name: 'projects'
    label: 'Projekty'
    folder: 'src/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Název projektu', name: 'title', widget: 'string' }
      - { label: 'Popis', name: 'description', widget: 'text' }
      - { label: 'Obrázek', name: 'image', widget: 'image' }
      - {
          label: 'Začátek realizace',
          name: 'start_date',
          widget: 'datetime',
          format: 'MM/YYYY',
          date_format: 'MM/YYYY',
          time_format: false,
        }
      - {
          label: 'Konec realizace',
          name: 'end_date',
          widget: 'datetime',
          format: 'MM/YYYY',
          date_format: 'MM/YYYY',
          time_format: false,
        }
      - {
          label: 'Pořadí (volitelné)',
          name: 'order',
          widget: 'number',
          required: false,
          hint: 'Menší číslo = vyšší pozice',
        }
